from pathlib import Path
path = Path(r"c:\xampp\htdocs\sistema_sso_stb\resources\views\riesgos\identificacion-guardar.blade.php")
text = path.read_text(encoding='utf-8')
marker = "  .status-dot--sin{ background:#b3261e; }"
idx = text.find(marker)
if idx == -1:
    raise SystemExit('marker not found')
insertion = "\n\n  .puesto-select{ display:flex; gap:8px; align-items:center; }\n  .puesto-select__input{ flex:1 1 auto; min-width:0; }\n  .puesto-select__btn{ flex:0 0 auto; padding:8px 12px; border:1px solid var(--border); border-radius:6px; background:#e7f6ff; font-size:12px; font-weight:600; cursor:pointer; color:#0f172a; transition:background-color .2s ease, box-shadow .2s ease; }\n  .puesto-select__btn:hover{ background:#d4ecff; box-shadow:0 1px 0 rgba(15,23,42,.18); }\n  .puesto-select__btn:focus{ outline:2px solid #44B3E1; outline-offset:2px; }\n\n  .modal{ position:fixed; inset:0; z-index:1100; display:none; align-items:center; justify-content:center; }\n  .modal.is-open{ display:flex; }\n  .modal__backdrop{ position:absolute; inset:0; background:rgba(15,23,42,.45); }\n  .modal__dialog{ position:relative; width:min(720px, 92%); max-height:85vh; background:#fff; border-radius:14px; box-shadow:0 24px 48px rgba(15,23,42,.25); display:flex; flex-direction:column; overflow:hidden; }\n  .modal__header{ padding:16px 20px; border-bottom:1px solid rgba(0,0,0,.08); display:flex; align-items:center; justify-content:space-between; gap:12px; }\n  .modal__title{ font-size:16px; font-weight:700; margin:0; }\n  .modal__close{ background:none; border:0; font-size:24px; line-height:1; cursor:pointer; color:#64748b; padding:4px; border-radius:6px; }\n  .modal__close:hover{ background:rgba(148,163,184,.15); color:#0f172a; }\n  .modal__body{ padding:16px 20px; display:flex; flex-direction:column; gap:12px; }\n  .modal__search input{ width:100%; padding:10px 12px; border:1px solid var(--border); border-radius:8px; font:inherit; }\n  .modal__list{ max-height:50vh; overflow:auto; border:1px solid var(--border); border-radius:10px; background:#fff; }\n  .modal__table{ width:100%; border-collapse:collapse; font-size:13px; }\n  .modal__table tbody tr{ cursor:pointer; transition:background-color .15s ease; }\n  .modal__table tbody tr:hover{ background:#f1f5f9; }\n  .modal__table td{ padding:10px 14px; border-bottom:1px solid rgba(15,23,42,.08); }\n  .modal__status{ text-align:right; white-space:nowrap; font-size:12px; color:#475569; }\n  .modal__row--ready .modal__status{ color:#1f7a35; }\n  .modal__row--pending .modal__status{ color:#b45309; }\n  .modal__row--active{ background:#e0f2fe !important; }\n  .modal__footer{ padding:12px 20px; border-top:1px solid rgba(0,0,0,.08); display:flex; justify-content:flex-end; gap:8px; }\n  .modal__btn{ appearance:none; border-radius:8px; border:1px solid var(--border); padding:8px 14px; font-weight:600; cursor:pointer; background:#fff; color:#0f172a; transition:background-color .2s ease; }\n  .modal__btn:hover{ background:#f1f5f9; }\n  .modal__btn--primary{ background:#44B3E1; border-color:#44B3E1; color:#fff; }\n  .modal__btn--primary:hover{ background:#1996cd; }\n  .modal__empty{ padding:16px; text-align:center; color:#64748b; display:none; }\n  body.modal-open{ overflow:hidden; }"
text = text[:idx+len(marker)] + insertion + text[idx+len(marker):]
path.write_text(text, encoding='utf-8')
